baseurl = "https://www.mikedrew.org/"
title = "Mike Drew"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"
#
staticDir = ["static"]

[params]
    author = "Mike Drew"
    avatar = "avatarSloth.png"
    favicon = "favicon.ico"
    description = """        
    """
    publicationYear = "2020"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]
    appInsights = "a73d2232-1c3a-484e-8274-6aa03e0d6876"

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    taxonomy = ["JSON", "HTML"]

[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/mikedrew"
    weight = 20

[[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/mikedrew123"
    weight = 25

[[menu.main]]
    identifier = "spotify"
    name = "Spotify"
    pre = "<i class='fab fa-spotify fa-lg'></i>"
    url = "https://open.spotify.com/user/mikedrew0110?si=uvFUMN4aQRONR6SNZzw59w"
    weight = 30

[[menu.main]]
    identifier = "email"
    name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:mike@mikedrew.org"
    weight = 40

[[menu.main]]
    identifier = "resume"
    name = "Resume"
    pre = "<i class='fa fa-file-alt fa-lg'></i>"
    url = "files/MikeDrewResume.pdf"
    weight = 50

[[menu.main]]
    identifier = "the90s"
    name = "The 90s"
    pre = "<i class='fas fa-rocket fa-lg'></i>"
    url = "90s.html"
    weight = 60


[deploymnet]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
#order = [".jpg$", ".gif$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "azuredeployment"

# Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
URL = "azblob://$web"

# [[deployment.matchers]] configure behavior for files that match the Pattern.
# Samples:

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
