name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: echo Hello, world!
    - uses: peaceiris/actions-hugo@v2.4.5
    - name: Builds site      
    - name: Deploys site
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  
