on:
  push:
    branches:
      - master

env:
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT_MIKEDREWDOTORG }}
  AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY_MIKEDREWDOTORG }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now
        # with:
        #   submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'
          # extended: true

      - name: Build
        run: hugo --minify
        
      - name: Deploy
        run: hugo deploy
      
      - name: Azure Login
        uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.0
        with:
          # Specify the script here
          inlineScript: 
            az cdn endpoint purge --resource-group mikedrew.org --profile-name mikedrewdotorgcdn --name mikedrewdotorgcdn --content-paths /*  
